chore: Improve api keys log
incubateur-ademe/impactco2 pull request #476
Opened 2023-11-09 11:09 UTC by desoindx

2023-11-10 09:13 UTC, bdavidxyz requested changes
Attention à mettre à jour le CHANGELOG ?

2023-11-10 11:19 UTC, desoindx commented
> Attention à mettre à jour le CHANGELOG ?

un changelog poru du log ? coté serveur ?

2023-11-10 13:18 UTC, bdavidxyz requested changes

2023-11-10 13:18 UTC, bdavidxyz commented on src/utils/middleware.ts
> +    console.error(`tracking failed - ${request.headers.authorization}`, error)
Pas de risque de sécurité de mettre un header d'autorisation dans les logs ?

2023-11-13 09:30 UTC, desoindx commented on src/utils/middleware.ts
> +    console.error(`tracking failed - ${request.headers.authorization}`, error)
Bonne question... je n'ai pas d'autres idées ?

2023-11-13 09:47 UTC, desoindx commented on src/utils/middleware.ts
> +    console.error(`tracking failed - ${request.headers.authorization}`, error)
sachant que ce n'est que en cas d'erreur => donc en cas d'utilisation incorrect
j'ai mis ca parcequ'on a eu des erreurs avec une ahturohization qui n'etait oas un uuid

2023-11-13 09:59 UTC, bdavidxyz requested changes

2023-11-13 09:59 UTC, bdavidxyz commented on src/utils/middleware.ts
> +    console.error(`tracking failed - ${request.headers.authorization}`, error)
hum ok. Dans ce cas je mettrai request?.headers?.authorization, si jamais request est null ou undefined.

2023-11-13 11:39 UTC, desoindx commented on src/utils/middleware.ts
> +    console.error(`tracking failed - ${request.headers.authorization}`, error)
request et headers est forcement definit, sinon c'est pas une requete http valide.
On pourrait, mais sentry est plus orienté front. La on a la main sur les logs

2023-11-13 11:46 UTC, bdavidxyz approved these changes

2023-11-13 18:22 UTC, merged