fix: hero display picture
incubateur-ademe/impactco2 pull request #498
Opened 2023-11-24 09:57 UTC by bdavidxyz

2023-11-27 08:26 UTC, desoindx requested changes
C'est pas du tout la solution proposé par Valentin...
Et les tests n'ont rien à faire dans cet PR, si on veut un histo propre

2023-11-27 08:26 UTC, desoindx commented on src/components/views/home/Hero.js
> +    font-size: 1.35rem;
Bizarre d'avoir une font size encore plus petite en encore plus grand

2023-11-28 09:01 UTC, bdavidxyz commented on src/components/views/home/Hero.js
> +    font-size: 1.35rem;
C'est pour laisser de la place à l'image justement, une fois qu'elle a disparu le texte peut reprendre toute sa place

2023-11-28 09:02 UTC, bdavidxyz commented
> C'est pas du tout la solution proposé par Valentin... Et les tests n'ont rien à faire dans cet PR, si on veut un histo propre

Pour les tests, c'est normal de "payer" un peu de dette tech à chaque PR

2023-11-28 09:16 UTC, desoindx commented on src/components/views/home/Hero.js
> +    font-size: 1.35rem;
non, elle s'affiche aussi en large et la police est plus grande

2023-11-28 10:28 UTC, closed without merging