[fix] TypeScript numerique
incubateur-ademe/impactco2 pull request #616
Opened 2024-02-06 10:52 UTC by bdavidxyz

2024-02-14 08:13 UTC, desoindx requested changes

2024-02-14 08:13 UTC, desoindx commented on src/components/numerique/equivalent/Bar.tsx
> +type BarType = { category: CategoryType; equivalent: EquivalentType; engine: Engine } & {
Pq ce & ?

2024-02-14 08:13 UTC, desoindx commented on src/components/numerique/equivalent/Detail.tsx
> +type LabeledEquivalentValue = EquivalentValue & {
Pq on a besoin d'un nouveau type ici ? normalement on passe que des equivalent non ?

2024-02-14 08:13 UTC, desoindx commented on src/components/numerique/equivalent/Detail.tsx
> +  interface Item {
C'est quoi cette interface ?

2024-02-14 08:13 UTC, desoindx commented on src/components/numerique/equivalent/Detail.tsx
> +              .sort((a: LabeledEquivalentValue, b: LabeledEquivalentValue) => {
tu devrais pas avoir besoin de le preciser

2024-02-14 08:13 UTC, desoindx commented on src/components/numerique/equivalent/Detail.tsx
> +              .map((item: LabeledEquivalentValue) => (
pareil

2024-02-14 08:13 UTC, desoindx commented on src/components/numerique/equivalent/ExpertMode.tsx
> +type Question = {
tu peux le faire directement en dessous

2024-02-26 15:28 UTC, desoindx commented on src/components/numerique/equivalent/Bar.tsx
> +type BarType = { category: CategoryType; equivalent: EquivalentType; engine: Engine; name: string; total: number }
tu peux inline le type, comme déjà demandé pour l'ExpertMode !

2024-02-27 09:42 UTC, bdavidxyz commented on src/components/numerique/equivalent/Bar.tsx
> +type BarType = { category: CategoryType; equivalent: EquivalentType; engine: Engine; name: string; total: number }
c'est quoi l'expert mode ?

2024-02-27 09:58 UTC, desoindx approved these changes

2024-02-27 13:33 UTC, merged