[fix] fruits&legumes emojis
incubateur-ademe/impactco2 pull request #621
Opened 2024-02-12 09:46 UTC by bdavidxyz

2024-02-14 08:13 UTC, desoindx approved these changes

2024-02-19 15:27 UTC, desoindx requested changes

2024-02-19 15:27 UTC, desoindx commented on src/components/views/equivalent/details/Value.tsx
> +  let emojiHeight = '1em'
tres chelou cette spécificité...

2024-02-19 15:52 UTC, bdavidxyz commented on src/components/views/equivalent/details/Value.tsx
> +  let emojiHeight = '1em'
oui c'est vrai, mais l'emoji est trop gros, donc on profite du fait que la taille de l'emoji soit configurable pour donner une taille plus intéressante.

2024-02-20 09:10 UTC, merged