[fix] make all bg screenshot as white
incubateur-ademe/impactco2 pull request #622
Opened 2024-02-12 09:59 UTC by bdavidxyz

2024-02-14 08:14 UTC, desoindx requested changes

2024-02-14 08:14 UTC, desoindx commented on src/hooks/useScreenshot.ts
> +        backgroundColor: 'white', // variables CSS non disponibles au moment du screenshot, valeur forcée à "white"
Ca va pas marcher sur du dark mode
et il me semble que c'est pas ca le ticket mais de rendre le bord transparent

2024-02-20 09:22 UTC, bdavidxyz commented on src/hooks/useScreenshot.ts
> +        backgroundColor: 'white', // variables CSS non disponibles au moment du screenshot, valeur forcée à "white"
Il reste un pb d'arrondi à corriger.

2024-02-20 12:11 UTC, bdavidxyz commented
@desoindx c'est validé par Valentin en recette

2024-02-20 18:26 UTC, desoindx approved these changes

2024-02-26 10:08 UTC, merged