[feat] New footer
incubateur-ademe/impactco2 pull request #623
Opened 2024-02-13 09:27 UTC by bdavidxyz

2024-02-14 08:21 UTC, desoindx requested changes

2024-02-14 08:21 UTC, desoindx commented on src/components/layout/web/Footer.tsx
> +const getOpenIcon = () => {
On a un composant Icon qui regroupe tout ca

2024-02-14 08:21 UTC, desoindx commented on src/components/layout/web/Footer.tsx
> +              </GridTwoA>
Affreux ces noms...

2024-02-14 08:21 UTC, desoindx commented on src/components/layout/web/Footer.tsx
> +const LinkContainer = styled.div`
Ca aurait ete cool de faire des modules css comme on a dit

2024-02-14 08:21 UTC, desoindx commented on src/components/screenshot/Signature.tsx
> +      <MarianneContainer>
Il est utilisé un peu partout celui la, tu as bien checké ?

2024-02-19 16:03 UTC, bdavidxyz commented on src/components/layout/web/Footer.tsx
> +              </GridTwoA>
c'est vrai... à rediscuter car je ne vois pas vraiment mieux pour l'instant

2024-02-19 16:04 UTC, bdavidxyz commented on src/components/screenshot/Signature.tsx
> +      <MarianneContainer>
alors j'utilise bien le Marianne utilisé un peu partout, j'ai juste rajouté un Container pour pouvoir bien le positionner.

2024-02-20 17:38 UTC, bdavidxyz commented on src/components/layout/web/Footer.tsx
> +const getOpenIcon = () => {
@desoindx un lien vers le composant en question?

2024-02-20 17:58 UTC, desoindx commented on src/components/layout/web/Footer.tsx
> +const getOpenIcon = () => {
https://github.com/incubateur-ademe/impactco2/blob/develop/src/components/osezchanger/icons/index.tsx

2024-02-27 14:51 UTC, desoindx requested changes

2024-02-27 14:51 UTC, desoindx commented on src/components/contact/SuggestionBanner.tsx
> +              <b>Un avis, une suggestion ?</b>
Pq on supprime ca ? la page permet de dire quand il y a un bug !

2024-02-27 14:51 UTC, desoindx commented on src/components/layout/web/Footer.module.css
> +  .gridlinks {
pq l'imbriquer ?

2024-02-27 14:51 UTC, desoindx commented on src/components/layout/web/Footer.module.css
> +      padding-right: 1.5rem;
Tu peux utiliser gap sur le container pour un truc plus propre

2024-02-27 14:51 UTC, desoindx commented on src/components/layout/web/Footer.module.css
> +.logo {
on a logos et logo ! chelou

2024-02-27 14:51 UTC, desoindx commented on src/components/layout/web/Footer.tsx
> +              <Link className={styles.last} href='https://beta.gouv.fr/' title='beta.gouv.fr' target='_blank'>
il existe pas ce style

2024-02-27 14:51 UTC, desoindx commented on src/components/layout/web/Footer.tsx
> +            <div className={styles.footerLink}>
pq mettre une div ici ? on peut pas mettre juste une liste de link ? avec leur propre classe ?

2024-02-27 14:51 UTC, desoindx commented on src/components/layout/web/Footer.tsx
> +                className={styles.githubLink}
style. qui n'existe pas

2024-02-27 14:52 UTC, bdavidxyz commented on src/components/layout/web/Footer.module.css
> +.logo {
il y a bien plusieurs logos (RF, ADEME...) et notre logo (le seul)

2024-02-27 14:54 UTC, bdavidxyz commented on src/components/layout/web/Footer.tsx
> +              <Link className={styles.last} href='https://beta.gouv.fr/' title='beta.gouv.fr' target='_blank'>
si! c'est le `a.last` dans Footer.module.css

2024-02-27 14:55 UTC, bdavidxyz commented on src/components/layout/web/Footer.tsx
> +                className={styles.githubLink}
exact, je supprime

2024-02-27 14:55 UTC, bdavidxyz commented on src/components/contact/SuggestionBanner.tsx
> +              <b>Un avis, une suggestion ?</b>
de mémoire, c'est une demande de Maxine

2024-02-27 14:55 UTC, bdavidxyz commented on src/components/layout/web/Footer.module.css
> +  .gridlinks {
exact, je désimbrique

2024-02-27 14:56 UTC, bdavidxyz commented on src/components/layout/web/Footer.tsx
> +            <div className={styles.footerLink}>
c'est vrai, ul li serait plus joli. Je corrige.

2024-02-27 15:09 UTC, bdavidxyz commented on src/components/layout/web/Footer.module.css
> +      padding-right: 1.5rem;
Ok c'est possible en gérant le gap avec le container du dessus, mais ca fait régresser les petites bordures grises. Je propose qu'on laisse en l'état vu que Valentin est ok côté design.

2024-02-27 16:45 UTC, desoindx commented on src/components/layout/web/Footer.tsx
> +              <Link className={styles.last} href='https://beta.gouv.fr/' title='beta.gouv.fr' target='_blank'>
pq a.last et pas just last dans ce cas la ? 
et si c'est un truc specifique tu as un selecteur css last-child

2024-02-29 10:14 UTC, merged